-- Focus Buddy schema for Supabase

create table if not exists public.focus_sessions (
  id bigint generated by default as identity primary key,
  client_session_id text unique,
  started_at timestamptz not null,
  ended_at timestamptz not null,
  session_ms integer not null check (session_ms >= 0),
  focus_ms integer not null check (focus_ms >= 0),
  focus_rate double precision not null check (focus_rate >= 0 and focus_rate <= 100),
  distraction_count integer not null check (distraction_count >= 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_focus_sessions_ended_at on public.focus_sessions (ended_at desc);
create index if not exists idx_focus_sessions_created_at on public.focus_sessions (created_at desc);

create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  title text not null,
  is_done boolean not null default false,
  due_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_todos_is_done_id on public.todos (is_done, id desc);
create index if not exists idx_todos_due_date on public.todos (due_date);

create table if not exists public.microsoft_auth_sessions (
  auth_session_id text primary key,
  access_token text not null,
  refresh_token text,
  expires_at bigint not null,
  display_name text,
  user_principal_name text,
  user_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_microsoft_auth_sessions_expires_at on public.microsoft_auth_sessions (expires_at desc);
create index if not exists idx_microsoft_auth_sessions_user_principal_name on public.microsoft_auth_sessions (user_principal_name);
